deplay test

diff --git a/.github/workflows/ci-docs.yml b/.github/workflows/ci-docs.yml
--- a/.github/workflows/ci-docs.yml
+++ b/.github/workflows/ci-docs.yml
@@ -22,12 +22,17 @@ jobs:
 
       - name: Install dependencies
         run: npm install --legacy-peer-deps
+      
+      # add 
+      - name: Build component library'
+        run: npm run build
 
       - name: Build docs
-        run: npm run build -w docs
+        # run: npm run build -w docs
+        run: npm run docs:build
 
       - name: List docs/dist contents
-        run: ls -la docs/.vitepress/dist || echo "docs/dist directory not found"
+        run: ls -la docs/.vitepress/dist/vitepress || echo "docs/dist directory not found"
 
   deploy-docs:
     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
